# # GUI

from tkinter import *
import joblib
def show_entry_fields():
 v1 = float(e1.get())
 v2 = float(e2.get())
 v3 = float(e3.get())
 v4 = float(e4.get())
 v5 = float(e5.get())
 v6 = float(e6.get())
 v7 = float(e7.get())
 v8 = float(e8.get())
 v9 = float(e9.get())
 v10 = float(e10.get())
 v11 = float(e11.get())
 v12 = float(e12.get())
 v13 = float(e13.get())
 v14 = float(e14.get())
 v15 = float(e15.get())
 v16 = float(e16.get())
 v17 = float(e17.get())
 v18 = float(e18.get())
 v19 = float(e19.get())
 v20 = float(e20.get())
 v21 = float(e21.get())
 v22 = float(e22.get())
 v23 = float(e23.get())
 v24 = float(e24.get())
 v25 = float(e25.get())
 v26 = float(e26.get())
 v27 = float(e27.get())
 v28 = float(e28.get())
 v29 = float(e29.get())
 model = joblib.load('credit_card_model')
 y_pred = model.predict([[v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29]])
 result = []
 if y_pred == 0:
    result.append('Normal Transaction')
 else:
    result.append('Fraudulent Transaction')
 
 print('Credit Card Fraud Detection System', result)

 Label(master, text='Final prediction from model-credit card fraud transaction').grid(row=32, columnspan=2)
 Label(master, text=result[0]).grid(row=33, columnspan=2)
master = Tk()
master.title('Credit Card Fraud Detection System')
Label(master, text='Credit Card Fraud Detection System', bg='black', fg='white', width=30).grid(row=0, columnspan=2)
Label(master, text='Enter value of V1').grid(row=1)
Label(master, text='Enter value of V2').grid(row=2)
Label(master, text='Enter value of V3').grid(row=3)
Label(master, text='Enter value of V4').grid(row=4)
Label(master, text='Enter value of V5').grid(row=5)
Label(master, text='Enter value of V6').grid(row=6)
Label(master, text='Enter value of V7').grid(row=7)
Label(master, text='Enter value of V8').grid(row=8)
Label(master, text='Enter value of V9').grid(row=9)
Label(master, text='Enter value of V10').grid(row=10)
Label(master, text='Enter value of V11').grid(row=11)
Label(master, text='Enter value of V12').grid(row=12)
Label(master, text='Enter value of V13').grid(row=13)
Label(master, text='Enter value of V14').grid(row=14)
Label(master, text='Enter value of V15').grid(row=15)
Label(master, text='Enter value of V16').grid(row=16)
Label(master, text='Enter value of V17').grid(row=17)
Label(master, text='Enter value of V18').grid(row=18)
Label(master, text='Enter value of V19').grid(row=19)
Label(master, text='Enter value of V20').grid(row=20)
Label(master, text='Enter value of V21').grid(row=21)
Label(master, text='Enter value of V22').grid(row=22)
Label(master, text='Enter value of V23').grid(row=23)
Label(master, text='Enter value of V24').grid(row=24)
Label(master, text='Enter value of V25').grid(row=25)
Label(master, text='Enter value of V26').grid(row=26)
Label(master, text='Enter value of V27').grid(row=27)
Label(master, text='Enter value of V28').grid(row=28)
Label(master, text='Enter value of V29').grid(row=29)
e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e5 = Entry(master)
e6 = Entry(master)
e7 = Entry(master)
e8 = Entry(master)
e9 = Entry(master)
e10 = Entry(master)
e11 = Entry(master)
e12 = Entry(master)
e13 = Entry(master)
e14 = Entry(master)
e15 = Entry(master)
e16 = Entry(master)
e17 = Entry(master)
e18 = Entry(master)
e19 = Entry(master)
e20 = Entry(master)
e21 = Entry(master)
e22 = Entry(master)
e23 = Entry(master)
e24 = Entry(master)
e25 = Entry(master)
e26 = Entry(master)
e27 = Entry(master)
e28 = Entry(master)
e29 = Entry(master)
e1.grid(row=1, column=1)
e2.grid(row=2, column=1)
e3.grid(row=3, column=1)
e4.grid(row=4, column=1)
e5.grid(row=5, column=1)
e6.grid(row=6, column=1)
e7.grid(row=7, column=1)
e8.grid(row=8, column=1)
e9.grid(row=9, column=1)
e10.grid(row=10, column=1)
e11.grid(row=11, column=1)
e12.grid(row=12, column=1)
e13.grid(row=13, column=1)
e14.grid(row=14, column=1)
e15.grid(row=15, column=1)
e16.grid(row=16, column=1)
e17.grid(row=17, column=1)
e18.grid(row=18, column=1)
e19.grid(row=19, column=1)
e20.grid(row=20, column=1)
e21.grid(row=21, column=1)
e22.grid(row=22, column=1)
e23.grid(row=23, column=1)
e24.grid(row=24, column=1)
e25.grid(row=25, column=1)
e26.grid(row=26, column=1)
e27.grid(row=27, column=1)
e28.grid(row=28, column=1)
e29.grid(row=29, column=1)
Button(master, text='Predict', command=show_entry_fields).grid(row=30, column=1)
mainloop()
